// Session mutations
export const SESSION_SET_ACCOUNT = "SESSION_SET_ACCOUNT";
export const SESSION_SET_WEB3_INSTANCE = "SESSION_SET_WEB3_INSTANCE";
export const SESSION_IS_ENABLED = "SESSION_IS_ENABLED";
export const WEB3_SESSION_CLEAR_ACCOUNT = "WEB3_SESSION_CLEAR_ACCOUNT";
export const SESSION_SET_RLOGIN = "SESSION_SET_RLOGIN";
export const SESSION_SET_RLOGIN_INSTANCE = "SESSION_SET_RLOGIN_INSTANCE";
export const SESSION_CLOSE_RLOGIN = "SESSION_CLOSE_RLOGIN";

// Session actions
export const WEB3_SESSION_GET_ACCOUNT = "WEB3_SESSION_GET_ACCOUNT";
export const SESSION_CONNECT_WEB3 = "SESSION_CONNECT_WEB3";
